name: Publish

on: 
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "nunonam@gmail.com"
      - run: git config --global user.name "nunonam"
      - run: npm version patch
      - run: git push origin main --tags 
      - uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
